local addonName, namespace = ...

local items = {
--Blood shards
   ["Shard of Bek"] = "Rank 1 Shard of Bek",
   ["Ominous Shard of Bek"] = "Rank 2 Shard of Bek",
   ["Desolate Shard of Bek"] = "Rank 3 Shard of Bek",
   ["Foreboding Shard of Bek"] = "Rank 4 Shard of Bek",
   ["Portentous Shard of Bek"] = "Rank 5 Shard of Bek",
   ["Shard of Jas"] = "Rank 1 Shard of Jas",
   ["Ominous Shard of Jas"] = "Rank 2 Shard of Jas",
   ["Desolate Shard of Jas"] = "Rank 3 Shard of Jas",
   ["Foreboding Shard of Jas"] = "Rank 4 Shard of Jas",
   ["Portentous Shard of Jas"] = "Rank 5 Shard of Jas",
   ["Shard of Rev"] = "Rank 1 Shard of Rev",
   ["Ominous Shard of Rev"] = "Rank 2 Shard of Rev",
   ["Desolate Shard of Rev"] = "Rank 3 Shard of Rev",
   ["Foreboding Shard of Rev"] = "Rank 4 Shard of Rev",
   ["Portentous Shard of Rev"] = "Rank 5 Shard of Rev",
--Frost Shards	  
   ["Shard of Cor"] = "Rank 1 Shard of Cor",
   ["Ominous Shard of Cor"] = "Rank 2 Shard of Cor",
   ["Desolate Shard of Cor"] = "Rank 3 Shard of Cor",
   ["Foreboding Shard of Cor"] = "Rank 4 Shard of Cor",
   ["Portentous Shard of Cor"] = "Rank 5 Shard of Cor",
   ["Shard of Tel"] = "Rank 1 Shard of Tel",
   ["Ominous Shard of Tel"] = "Rank 2 Shard of Tel",
   ["Desolate Shard of Tel"] = "Rank 3 Shard of Tel",
   ["Foreboding Shard of Tel"] = "Rank 4 Shard of Tel",
   ["Portentous Shard of Tel"] = "Rank 5 Shard of Tel",
   ["Shard of Kyr"] = "Rank 1 Shard of Kyr",
   ["Ominous Shard of Kyr"] = "Rank 2 Shard of Kyr",
   ["Desolate Shard of Kyr"] = "Rank 3 Shard of Kyr",
   ["Foreboding Shard of Kyr"] = "Rank 4 Shard of Kyr",
   ["Portentous Shard of Kyr"] = "Rank 5 Shard of Kyr",
--Unholy Shards
   ["Shard of Dyz"] = "Rank 1 Shard of Dyz",
   ["Ominous Shard of Dyz"] = "Rank 2 Shard of Dyz",
   ["Desolate Shard of Dyz"] = "Rank 3 Shard of Dyz",
   ["Foreboding Shard of Dyz"] = "Rank 4 Shard of Dyz",
   ["Portentous Shard of Dyz"] = "Rank 5 Shard of Dyz",
   ["Shard of Zed"] = "Rank 1 Shard of Zed",
   ["Ominous Shard of Zed"] = "Rank 2 Shard of Zed",
   ["Desolate Shard of Zed"] = "Rank 3 Shard of Zed",
   ["Foreboding Shard of Zed"] = "Rank 4 Shard of Zed",
   ["Portentous Shard of Zed"] = "Rank 5 Shard of Zed",
   ["Shard of Oth"] = "Rank 1 Shard of Oth",
   ["Ominous Shard of Oth"] = "Rank 2 Shard of Oth",
   ["Desolate Shard of Oth"] = "Rank 3 Shard of Oth",
   ["Foreboding Shard of Oth"] = "Rank 4 Shard of Oth",
   ["Portentous Shard of Oth"] = "Rank 5 Shard of Oth",
}

namespace.items = items